on:
  release:
      types: [released, published]
  workflow_dispatch:

jobs:
  build:
    name: Rebuild editor
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3.9.1
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - uses: actions/upload-pages-artifact@3.0.1
        with:
          name: "github-pages"
          path: "./build"
          
  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
